language: node_js
node_js:
  - 6.0.0
  - 5.0.0
  - 4.0.0
  - 0.12
  - 0.11
  - 0.10
  - iojs-v3.0.0
  - iojs-v2.0.0
  - iojs-v1.0.0
sudo: false
script:
  - npm run test-ci
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
addons:
  code_climate:
    repo_token:
      secure: "mAwYHoa4Xt/Hnaj48PuhAmKFEduX32RR5vc7YoGbUhPOazIcBfmywFN8upB1eARAdoqtDC1nEU6tVigSwS/f6LAjFYCPpoBRqKgewWe2ore6jTMPz67BPWrZz5pl7YKeqF4Q1OD8Xq2MJpPQTLk0ffcS0rpi2az/UZbvrG/0l+JvFoq5d6A05eFfmmh4PvgU26XaaJUhsKJiFmYCYjZgtvQllUa7Hr4S41MQoj5l17omKYMb51pI2JOQeeROxDw01nCLqEbJ+tehjaXxputQ1rSORhohOyNPQC4OtKhlSj8QN25xTFReQmlNRnUKlUL87iUGCgg6mIh2d2HHWwJ74EiFEM/AoILLjpqZiaPWwapvktTiVhBORMeLEOfcNbBi9uD4+rAK3Eq4ZB7hfy5Igrvy2Me0XpFZinfrEx2cmui0dVLPZmqr81Xvb1xTBr2oao73S4L89I3No0CTnOizStrrKnqQvRB/m4x04uSYFoWP56Nx684JOPQcXn/sOwhfy9xSfQ/QSv0ZbO8tl4drU59nPZNzdQs1S9vC0A2O0zxlncG/0wUeT09SQoehPTog9RXEawUOw5wQW3KxTEX2LL9T7ZCGU8pz0qkiEnCLCXBx/zMskw/o91sxFTxp0zOPzG8Sq7MEA32wO7F5TNZrMB+L/64UGoLEO8HqSQ0izg0="